<script lang="ts">
  import { onMount } from 'svelte';
  import { browser } from '$app/environment';
  import { page } from '$app/stores';
  import type { SpasmEventV2 } from '$lib/types/interfaces';
  import { spasm } from '$lib/spasm';
  import { config } from '$lib/config';
  import { useAppConfigStore } from '$lib/stores/useAppConfigStore.svelte';
  import { useProfilesStore } from '$lib/stores/useProfilesStore.svelte';
  import { useUtils } from '$lib/utils/useUtils';
  import { useNostr } from '$lib/utils/useNostr';
  import { useMocks } from '$lib/utils/useMocks';
  import { useFetch } from '$lib/utils/useFetch';
  import ExtraBlockies from '$lib/components/extra/ExtraBlockies.svelte';
  import ExtraAddressIcons from '$lib/components/extra/ExtraAddressIcons.svelte';
  import ExtraRssBlock from '$lib/components/extra/ExtraRssBlock.svelte';
  import IconsExternalWebsite from '$lib/components/icons/IconsExternalWebsite.svelte';
  import InfoEventCommentsCard from '$lib/components/info/InfoEventCommentsCard.svelte';

  const enableAutoGeneratedNames =
    config?.enableAutoGeneratedNames === 'false' ? false : true;

  const { areValidSpasmEventsV2, autoGeneratedName, hasValue, isArrayWithValues } =
    useUtils();
  const { toBeHex, toBeNpub, isHex, isNostrValue } = useNostr();
  const profilesStore = useProfilesStore();
  const apiURL = useAppConfigStore()?.getApiUrl;
  const { getMockEventsByAddress } = useMocks();
  const useMockedDataIfBackendIsDown =
    config?.useMockedDataIfBackendIsDown === 'true';

  // Route param. The component is reused across /authors/A ->
  // /authors/B, so derive from $page and react to changes.
  const author = $derived.by(() => {
    const id = $page.params.id;
    if (id && typeof id === 'string') return id.toLowerCase();
    return '';
  });

  const npub = $derived.by(() => {
    if (author && typeof author === 'string') {
      if (author.length === 64 && isHex(author)) return toBeNpub(author);
      if (isNostrValue(author)) return author;
    }
    return null;
  });

  const nostrHex = $derived.by(() => {
    if (author && typeof author === 'string') {
      if ((author.length === 64 && isHex(author)) || isNostrValue(author)) {
        return toBeHex(author);
      }
    }
    return null;
  });

  let selectedNetworkToDisplay = $state('spasm');
  const selectNetworkToDisplay = (newNetwork: string): void => {
    if (!newNetwork) return;
    selectedNetworkToDisplay = newNetwork;
  };

  let nerdyDetailsShown = $state(false);
  const toggleNerdyDetails = () => {
    nerdyDetailsShown = !nerdyDetailsShown;
  };

  let showActionDetails = $state(false);
  let showActionDetailsText = $state('show');
  const toggleShowActionDetails = (): void => {
    showActionDetails = !showActionDetails;
    showActionDetailsText = showActionDetailsText === 'show' ? 'hide' : 'show';
  };

  let posts: SpasmEventV2[] = $state([]);

  const preferredRelays = $derived.by(() => {
    const relays = profilesStore.getPreferredRelaysFromAddress(author);
    return Array.isArray(relays) ? relays : [];
  });

  // The metadata getter can return string | string[]; coerce the
  // picture to a string for the <img src>.
  const profilePicture = $derived.by(() => {
    const pic = profilesStore.getMetadataByAddressNostr(author, 'picture');
    return typeof pic === 'string' ? pic : '';
  });

  const nostrMessages = $derived(
    profilesStore.getMessagesByAddressNostr(author)
  );
  const nostrSpasmEvents = $derived.by(() => {
    const converted = spasm.convertManyToSpasm(nostrMessages);
    return Array.isArray(converted) ? converted : [];
  });

  const scrollToTop = () => {
    const element = document.querySelector('#top-anchor');
    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'end' });
    }
  };

  const fetchPosts = async (signer: string) => {
    // Comments are fetched on the client because event
    // sanitization with DOMPurify inside convertManyToSpasm()
    // only works in a browser environment.
    const path = `${apiURL}/api/events?signer=${signer}&action=post&action=reply`;
    const { data, error } = await useFetch(path);
    if (error.value) {
      console.error(error.value);
    }
    if (data?.value) {
      const spasmEvents = spasm.convertManyToSpasm(data.value);
      if (spasmEvents && areValidSpasmEventsV2(spasmEvents)) {
        posts = spasmEvents;
      }
    } else if (useMockedDataIfBackendIsDown) {
      posts = getMockEventsByAddress(signer);
    }
  };

  onMount(() => {
    // Scroll to the top when the author changes. Small delay to
    // allow the DOM to update.
    setTimeout(scrollToTop, 300);
  });

  // Refetch posts and queue profile updates whenever the author
  // changes (navigation reuses this component).
  $effect(() => {
    const currentAuthor = author;
    if (!currentAuthor || typeof currentAuthor !== 'string') return;
    profilesStore.addAddress(currentAuthor, ['username', 'relays', 'messages']);
    profilesStore.updateAllProfiles(['relays', 'username', 'messages']);
    void fetchPosts(currentAuthor);
  });
</script>

<div class="p-2">
  {#if browser}
    <span id="top-anchor"></span>
    {#if profilePicture && profilePicture !== 'none'}
      <div class="h-20 overflow-hidden">
        <img src={profilePicture} alt="Nostr profile picture" class="h-20 object-cover" />
      </div>
    {:else}
      <div class="h-20 overflow-hidden">
        {#if author}<ExtraBlockies seed={author} scale={10} />{/if}
      </div>
    {/if}
  {/if}

  <div class="mt-2">
    {#if enableAutoGeneratedNames}
      <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
        Auto-generated name:
      </div>
      <span class="overflow-auto overflow-wrap break-words">
        <span>{autoGeneratedName(author)}</span>
      </span>
    {/if}
    {#if npub}
      <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
        <span>Address (hex):</span>
      </div>
      <span class="overflow-auto overflow-wrap break-words">{nostrHex}</span>
      {#if nostrHex}
        <ExtraAddressIcons
          value={nostrHex}
          showFollow={true}
          showCopyToClipboard={true}
          showQrCode={true}
          showExternalWebsite={true}
        />
      {/if}
    {:else}
      <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
        <span>Address:</span>
      </div>
      <span class="overflow-auto overflow-wrap break-words">{author}</span>
      {#if author}
        <ExtraAddressIcons
          value={author}
          showFollow={true}
          showCopyToClipboard={true}
          showQrCode={true}
          showExternalWebsite={true}
        />
      {/if}
    {/if}
  </div>

  {#if npub}
    <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
      Address (npub):
    </div>
    <span class="overflow-auto overflow-wrap break-words">{npub}</span>
    <ExtraAddressIcons
      value={npub}
      showFollow={true}
      showCopyToClipboard={true}
      showQrCode={true}
      showExternalWebsite={true}
    />
    <span class="block mt-1 mb-2 cursor-pointer">
      <a
        href={`nostr:${npub}`}
        target="_blank"
        class="text-colorNotImportant-light dark:text-colorNotImportant-dark hover:text-colorPrimary-light dark:hover:text-colorPrimary-dark"
      >
        Open in your Nostr app
        <IconsExternalWebsite class="custom-icons-large lg:custom-icons pb-1" />
      </a>
    </span>
  {/if}

  {#if browser}
    {#if profilesStore.getMetadataByAddressNostr(author, 'username') && profilesStore.getMetadataByAddressNostr(author, 'username') !== 'none'}
      <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">Name:</div>
      <span class="text-xl font-bold">
        {profilesStore.getMetadataByAddressNostr(author, 'username')}
      </span>
      <span class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
        (non-unique Nostr name)
      </span>
    {/if}

    {#if profilesStore.getMetadataByAddressNostr(author, 'about') && profilesStore.getMetadataByAddressNostr(author, 'about') !== 'none'}
      <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">About:</div>
      <span class="">{profilesStore.getMetadataByAddressNostr(author, 'about')}</span>
    {/if}

    {#if profilesStore.getMetadataByAddressNostr(author, 'website') && profilesStore.getMetadataByAddressNostr(author, 'website') !== 'none'}
      <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">Website:</div>
      <span class="">{profilesStore.getMetadataByAddressNostr(author, 'website')}</span>
    {/if}

    <!-- Nerdy details -->
    {#if isArrayWithValues(preferredRelays)}
      <button onclick={() => toggleNerdyDetails()} class="py-2">
        <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
          More nerdy details
          <svg
            class="w-5 h-5 inline"
            class:rotate-180={nerdyDetailsShown}
            viewBox="0 0 20 20"
            fill="currentColor"
          >
            <path
              fill-rule="evenodd"
              d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
              clip-rule="evenodd"
            />
          </svg>
        </div>
      </button>
    {/if}
    {#if nerdyDetailsShown}
      {#if isArrayWithValues(preferredRelays)}
        <div class="">
          <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
            Preferred relays:
          </div>
          {#each preferredRelays as relay}
            {#if relay}<div>{relay}</div>{/if}
          {/each}
        </div>
      {/if}
    {/if}
  {/if}

  <ExtraRssBlock
    class="my-2"
    signer={npub || author}
    activity={'all'}
    showActivityFilter={true}
    showSignerFilter={true}
    showCategoryFilter={true}
    enablePosts={true}
    enableComments={true}
  />

  <!--
    Rendered client-side to avoid hydration mismatch, but that is
    bad for SEO because the author's posts are not server-rendered
    and so are not indexed by crawlers.
  -->
  {#if browser}
    <div class="mt-4 mb-12">
      <div class="text-lg">
        Networks:
        <span
          class="cursor-pointer text-colorNotImportant-light dark:text-colorNotImportant-dark {selectedNetworkToDisplay === 'spasm' ? 'text-colorPrimary-light dark:text-colorPrimary-dark' : ''}"
          onclick={() => selectNetworkToDisplay('spasm')}
        >
          Spasm
        </span>
        {#if npub}
          <span
            class="cursor-pointer text-colorNotImportant-light dark:text-colorNotImportant-dark {selectedNetworkToDisplay === 'nostr' ? 'text-colorPrimary-light dark:text-colorPrimary-dark' : ''}"
            onclick={() => selectNetworkToDisplay('nostr')}
          >
            Nostr
          </span>
        {/if}
      </div>
      <div
        class="cursor-pointer text-colorNotImportant-light dark:text-colorNotImportant-dark mb-4 hover:text-colorPrimary-light dark:hover:text-colorPrimary-dark"
        onclick={() => toggleShowActionDetails()}
      >
        {showActionDetailsText} details
      </div>

      <!-- Spasm network -->
      {#if selectedNetworkToDisplay === 'spasm'}
        <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
          Spasm network:
        </div>
        {#if areValidSpasmEventsV2(posts)}
          {#each posts as post (post.ids?.[0]?.value)}
            <InfoEventCommentsCard
              comment={post}
              showCommentsCount={false}
              showActionDetails={showActionDetails}
            />
          {/each}
        {/if}
      {/if}

      <!-- Nostr network -->
      {#if selectedNetworkToDisplay === 'nostr'}
        {#if hasValue(nostrMessages)}
          <div class="text-colorNotImportant-light dark:text-colorNotImportant-dark">
            Nostr network:
          </div>
          <span class="">
            {#each nostrSpasmEvents as event (event?.ids?.[0]?.value)}
              <InfoEventCommentsCard
                comment={event}
                showActionDetails={showActionDetails}
                showCommentsCount={false}
              />
            {/each}
          </span>
        {/if}
      {/if}
    </div>
    <div
      class="w-32 mt-1 mb-16 cursor-pointer text-colorNotImportant-light dark:text-colorNotImportant-dark"
      onclick={() => scrollToTop()}
    >
      Scroll to top
    </div>
  {/if}
</div>
